# Generated by Django 3.1.7 on 2021-03-31 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoquepecas', '0001_initial'),
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manutentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencias.funcionario', verbose_name='Manutentor')),
            ],
            options={
                'verbose_name': 'Manutentor',
                'verbose_name_plural': 'Manutentores',
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroOrdemServico', models.SmallIntegerField(verbose_name='Numero Ordem Serviço')),
                ('tipoServicos', models.CharField(blank=True, choices=[('Preventiva', 'Preventiva'), ('Corretiva', 'Corretiva'), ('Preditiva', 'Preditiva')], max_length=15, null=True, verbose_name='Tipo de Manutenção')),
                ('Turno', models.CharField(choices=[('A', 'Primeiro'), ('B', 'Segundo'), ('C', 'Terceiro')], max_length=30, verbose_name='Turno')),
                ('dataCriacao', models.DateField(auto_now=True, null=True, verbose_name='Criado em')),
                ('dataProgramada', models.DateField(blank=True, null=True, verbose_name='Programado para')),
                ('dataExecucao', models.DateField(blank=True, null=True, verbose_name='Executado em')),
                ('tipoManutencao', models.CharField(choices=[('ELE', 'ELETRICA'), ('MEC', 'MECANICA'), ('LUB', 'LUBRIFICACAO'), ('CIV', 'CIVIL')], max_length=15, verbose_name='Tipo de Manutenção')),
                ('status', models.CharField(choices=[('Aberta', 'Aberta'), ('Fechada', 'Fechada'), ('Cancelada', 'Cancelada')], max_length=10, verbose_name='Status')),
                ('quantidade_material', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('imagensAntes', models.ImageField(blank=True, null=True, upload_to='ImagemAntes', verbose_name='Imagem antes')),
                ('imagemDepois', models.ImageField(blank=True, null=True, upload_to='ImagemDepois', verbose_name='Imagem Depois')),
                ('Descricao', models.TextField(verbose_name='Descrição Serviço')),
                ('Manutentores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controleordens.manutentor')),
                ('Material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoquepecas.item')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencias.maquina')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
            },
        ),
    ]
