# Generated by Django 3.1.7 on 2021-04-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleordens', '0002_auto_20210405_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='numeroOrdemServico',
            field=models.SmallIntegerField(verbose_name='Numero Ordem Serviço'),
        ),
    ]
