# Generated by Django 3.1.7 on 2021-03-31 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('funcao', models.CharField(max_length=30, verbose_name='Função')),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeMaquina', models.CharField(max_length=30, unique=True, verbose_name='Nome Máquina')),
            ],
        ),
        migrations.CreateModel(
            name='ParadaDeMaquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoServico', models.CharField(choices=[('ELE', 'ELETRICA'), ('MEC', 'MECANICA'), ('LUB', 'LUBRIFICACAO'), ('CIV', 'CIVIL')], default='ELETRICA', max_length=30, null=True, verbose_name='Tipo de Serviço')),
                ('tipoManutencao', models.CharField(choices=[('Corretiva', 'Corretiva'), ('Preventiva', 'Preventiva')], default='Preventiva', max_length=15, null=True, verbose_name='Motivo')),
                ('horaOcorencia', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Ocorencia')),
                ('horaReinicio', models.DateTimeField(null=True, verbose_name='Data Reinicio')),
                ('duracao', models.DateTimeField(null=True, verbose_name='Duração')),
                ('turno', models.CharField(choices=[('1°', 'Primeiro'), ('2°', 'Segundo'), ('3°', 'Terceiro'), ('ADM', 'Administrativo')], max_length=30, null=True, verbose_name='Turno')),
                ('descricao', models.TextField(max_length=150, null=True, verbose_name='Descrição')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencias.maquina')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencias.funcionario')),
            ],
        ),
    ]
