# Generated by Django 3.1.7 on 2021-03-31 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducaoMaquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrdemProd', models.IntegerField(blank=True, null=True, verbose_name='Ordem De Produção')),
                ('ProdDia', models.IntegerField(verbose_name='Produção Do Dia')),
                ('ProdDataInicio', models.DateTimeField(verbose_name='Inicio Produção')),
                ('ProdDataFim', models.DateField(verbose_name='Fim Produção')),
                ('Produto', models.IntegerField(verbose_name='Código Produto')),
                ('Equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencias.maquina')),
                ('Operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencias.funcionario')),
            ],
            options={
                'verbose_name': 'Produção de Máquina',
                'verbose_name_plural': 'Produção de Máquinas',
            },
        ),
    ]
